### ISSUE TITLE
dependencies not registered

### ISSUE THREAD

**Issue by ByJC** [telerik/ng2-dashboard#11]
Hi, 

I wanted to run your project but when i tried to install the dependencies, i got the following error : 

```
npm ERR! 404 Not found : @progress/kendo-angular-inputs
npm ERR! 404
npm ERR! 404  '@progress/kendo-angular-inputs' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular2-webpack-starter'
```
it seems the kendo dependencies are not register, so i wonder how did you install the dependencies ?

**Comment by rkonstantinov** [comment]
Did you follow the steps outlined here -> http://www.telerik.com/kendo-angular-ui/getting-started/#installation?

**Comment by ByJC** [comment]
I did not follow this steps, my bad.
I was not aware of it when i found this repository.
Sorry for the issue.
