### ISSUE TITLE
Module dependency 'marked' is missing for web platform implementation.

### ISSUE THREAD

**Issue by JELaVallee** [telerik/ng2-dashboard#12]
* **I'm submitting a ...**
[ X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Bug - configuration gap

* **What is the current behavior?**
When running `npm start` to kick off the web platform packaging/deployment there is the dependency error in the webpack loader init:

```
ERROR in ./web/app/markdown/markdown.component.ts
Module not found: Error: Cannot resolve module 'marked' in /Volumes/Neuromancer/Users/jelavallee/Development/nativescript/ns-ng2-kendoui/ng2-dashboard/web/app/markdown
 @ ./web/app/markdown/markdown.component.ts 3:13-30
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 536 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./web/index.html 1.95 kB {0} [built]
           factory:38ms building:160ms = 198ms
        [1] ./~/html-webpack-plugin/~/lodash/lodash.js 533 kB {0} [built]
           [0] 198ms -> factory:783ms building:346ms = 1327ms
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
           [0] 198ms -> [1] 1129ms -> factory:103ms building:384ms = 1814ms
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

From the master branch clone:

``` 
npm install

npm start

...

## Above error...

```

Adding the 'marked' module to the root package.json appears to have fixed the issue.  Sending a PR shortly...

**Comment by vakrilov** [comment]
Thanks for the PR @JELaVallee
