### ISSUE TITLE
Error when try to run {N} 

### ISSUE THREAD

**Issue by lilkren** [telerik/ng2-dashboard#15]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**
Trying to follow README at telerik/ng2-dashboard

Error when trying to run "npm run start-ios"

```
4:41:11 PM tns-sync.1 |  Oct 19 16:41:11 Lees-Mac-mini ng2dashboard[6002]: file:///app/vendor.js:59096:78: JS ERROR Error: Error in ./IssuesComponent class IssuesComponent - inline template:18:8 caused by: Can't find variable: TNSLabel

4:41:11 PM tns-sync.1 |  Oct 19 16:41:11 Lees-Mac-mini com.apple.CoreSimulator.SimDevice.3715AA82-D60A-4D18-BD64-429CEBA6D231.launchd_sim[77327] (UIKitApplication:org.nativescript.ngrc5[0x19dd][6002]): Service exited due to Segmentation fault: 11
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a 
Here are the steps I followed

```
git clone https://github.com/telerik/ng2-dashboard.git

npm login --registry=https://registry.npm.telerik.com/ --scope=@progress

npm view @progress/kendo-angular-grid versions

> [ '0.2.1', '0.2.2', '0.3.0', '0.3.1', '0.3.2', '0.3.3' ]

=== NPM Scoping working! Enough with huggin ... on with the killin ... 

npm install

npm start

==== http://localhost:3000/ === Works like a champ ... except some minor styling issues 

==== Now for {N} =====

 nativescript --version 

> 2.3.0

=== Ran "npm install" earlier ===
npm run prepare-ios
npm run start-ios

=== Boom!  ===

4:41:11 PM tns-sync.1 |  Oct 19 16:41:11 Lees-Mac-mini ng2dashboard[6002]: file:///app/vendor.js:59096:78: JS ERROR Error: Error in ./IssuesComponent class IssuesComponent - inline template:18:8 caused by: Can't find variable: TNSLabel

4:41:11 PM tns-sync.1 |  Oct 19 16:41:11 Lees-Mac-mini com.apple.CoreSimulator.SimDevice.3715AA82-D60A-4D18-BD64-429CEBA6D231.launchd_sim[77327] (UIKitApplication:org.nativescript.ngrc5[0x19dd][6002]): Service exited due to Segmentation fault: 11

```

* **What is the expected behavior?**
Run NativeScript iOS as seen in https://www.youtube.com/watch?v=ezUX5-kJbrU

* **What is the motivation / use case for changing the behavior?**
Testing

* **Please tell us about your environment:**

```
 nativescript --version 
> 2.3.0
npm --version
> 3.9.3
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by vakrilov** [comment]
It looks a lot like NativeScript/NativeScript#2583.
It is usually caused by a wrong version of the `tns-core-modules-widgets` package being installed. 
You can try deleting platforms folder and rebuilding or ultimately adding the `"tns-core-modules-widgets": "2.3.0"` in the package.json dependencies.

**Comment by lilkren** [comment]
@vakrilov thanks for responding.
As suggested I removed the platforms folder and tried 

```
npm run prepare-ios
npm run start-ios
```
I can see 

```
├─┬ tns-core-modules@2.3.0 
│ └── tns-core-modules-widgets@2.3.0 

```
and

`Successfully prepared plugin tns-core-modules-widgets for ios.
`
But still ... same error....

Then I added the following to the package.json
```
...
   "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "2.3.0",
    **"tns-core-modules-widgets": "2.3.0",**
    "zone.js": "0.6.23"
....
```

and tried 

```
npm run prepare-ios
npm run start-ios
```

No joy ...

Then tried the old {N} staple ... "**Scortched Earth**" 

```
rm -R ng2-dashboard
npm uninstall -g nativescript
npm cache clean
npm install -g nativescript
nativescript --version 
> 2.3.0
git clone https://github.com/telerik/ng2-dashboard.git
=== Add "tns-core-modules-widgets": "2.3.0", to package.json and save ==
npm install
npm run prepare-ios
npm run start-ios
```

...and still ... no joy ... same error

**Comment by vakrilov** [comment]
OK, It look like it might be related to another issue (NativeScript/nativescript-cli#2110) when preparing plugins with the `--bundle` option (which is needed for webpack and used in the npm scripts in this project)
The workaround for that is to execute `tns prepare ios` once (after the `npm install` and before run) to make sure all the plugins are properly prepared.

**Comment by lilkren** [comment]
Based on previous comment ... tried the following

```
rm -R ng2-dashboard/node_modules
rm -R ng2-dashboard/platforms
npm install
tns prepare ios
npm run start-ios
```

... and ... still same error

for giggles also tried 

```
rm -R ng2-dashboard/node_modules
rm -R ng2-dashboard/platforms
npm install
tns prepare ios
npm run prepare-ios
npm run start-ios
```

Still no joy

**Comment by vakrilov** [comment]
I tried with a fresh copy of the repo and the following setup:
```
npm -v ----> 3.10.3
node -v ---> v6.7.0
tns --version  --->2.3.0
```
The following seemed to work with me on Mac with iOS 9.2 Simulator:

```
npm install
npm run prepare-ios
npm run start-ios
```

I think that only difference is the `npm` version although this is a long shot.

**Comment by lilkren** [comment]
@vakrilov ... The npm or node version musta been the issue ... used ["n"](https://github.com/tj/n) to update both ... and now I am at

npm -v ----> 3.10.8
node -v ---> v6.9.1
tns --version  ---> 2.3.0

.... and {N} iOS version is now working nicely!

Thanks for your patience and quick responses!
