### ISSUE TITLE
npm ERR! 404 Not found : @progress/kendo-angular-charts

### ISSUE THREAD

**Issue by NathanWalker** [telerik/ng2-dashboard#16]
When doing `npm i`:

> npm ERR! 404 Not found : @progress/kendo-angular-charts
npm ERR! 404 
npm ERR! 404  '@progress/kendo-angular-charts' is not in the npm registry.

**Comment by KirilNN** [comment]
Hi,

Do you think that it might be something like this - https://github.com/telerik/ng2-dashboard/issues/11

**Comment by NathanWalker** [comment]
Thank you @KirilNN yep that explains it 👍

**Comment by KirilNN** [comment]
@Catchops - can you try to run `npm i @progress/kendo-angular-layout` in a different project? If it fails, please share with us you `.npmrc` file.

**Comment by Catchops** [comment]
@KirilNN - just installed on fresh project, but no failures.

**Comment by Catchops** [comment]
@KirilNN Just an update - I completely removed EVERYTHING (npm uninstall XXX) regarding anything kendo-angular and started over and now it looks like I am getting the correct javascript files loading.  Not sure why it is working this time.  I followed the same directions both times.  This time they are loading.  The problem I am getting now is that the 'kendo-panelbar-item' is not a known element.  But that is a different error.  I'm INCHING along here!

**Comment by tsvetomir** [comment]
Try `rm -r node_modules && npm i`, sometimes dependencies get messed up for no reason.

**Comment by kirhhof** [comment]
An ugly solution would be to delete the folders/files from node_modules folder
and after that run the install command that will automatically pull all the dependencies.
