### ISSUE TITLE
"Application entry point file not found" with node 6.9.4

### ISSUE THREAD

**Issue by Milo711** [telerik/ng2-dashboard#19]
Hi,
I'm having a problem running the mobile app. (website works fine)

I started a fresh project. Here are my steps:
run cmd as administrator
cd C:\NSKendo
git clone https://github.com/telerik/ng2-dashboard.git
cd ng2-dashboard
npm login --registry=https://registry.npm.telerik.com/ --scope=@progress
username
password
npm install
npm run prepare-android
npm run start-android

then I got error:

> angular2-webpack-starter@5.0.5 prestart-android C:\NSKendo\ng2-dashboard
> npm run ns-clean

> angular2-webpack-starter@5.0.5 ns-clean C:\NSKendo\ng2-dashboard
> shx rm -rf app/**/*.css app/**/*.js

> angular2-webpack-starter@5.0.5 start-android C:\NSKendo\ng2-dashboard
> nf -j Procfile.android start

[WARN] No ENV file found
1:45:49 PM webpack.1  |  > angular2-webpack-starter@5.0.5 ns-webpack-android C:\NSKendo\ng2-dashboard
1:45:49 PM webpack.1  |  > webpack --config=config/mobile/webpack.android.js "--watch"
1:45:49 PM tns-sync.1 |  > angular2-webpack-starter@5.0.5 ns-start-sync-android C:\NSKendo\ng2-dashboard
1:45:49 PM tns-sync.1 |  > node config/wait-for-bundle.js android && npm run ns-livesync-android
1:45:55 PM webpack.1  |  Error: Debug Failure. False expression: File  has unknown extension.
1:45:55 PM webpack.1  |      at Object.assert (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:3168:23)
1:45:55 PM webpack.1  |      at Object.fail (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:3173:19)
1:45:55 PM webpack.1  |      at Object.extensionFromPath (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:3315:15)
1:45:55 PM webpack.1  |      at C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:62592:46
1:45:55 PM webpack.1  |      at Array.map (native)
1:45:55 PM webpack.1  |      at resolveModuleNamesWorker (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:62586:141)
1:45:55 PM webpack.1  |      at resolveModuleNamesReusingOldState (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:62770:24)
1:45:55 PM webpack.1  |      at processImportedModules (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63565:35)
1:45:55 PM webpack.1  |      at findSourceFile (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63475:17)
1:45:55 PM webpack.1  |      at processSourceFile (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63378:27)
1:45:55 PM webpack.1  |      at C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63488:17
1:45:55 PM webpack.1  |      at Object.forEach (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:1293:30)
1:45:55 PM webpack.1  |      at processReferencedFiles (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63486:16)
1:45:55 PM webpack.1  |      at findSourceFile (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63471:21)
1:45:55 PM webpack.1  |      at processSourceFile (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63378:27)
1:45:55 PM webpack.1  |      at C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63488:17
1:45:55 PM webpack.1  |      at Object.forEach (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:1293:30)
1:45:55 PM webpack.1  |      at processReferencedFiles (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63486:16)
1:45:55 PM webpack.1  |      at findSourceFile (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63471:21)
1:45:55 PM webpack.1  |      at processSourceFile (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63378:27)
1:45:55 PM webpack.1  |      at C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63488:17
1:45:55 PM webpack.1  |      at Object.forEach (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:1293:30)
1:45:55 PM webpack.1  |      at processReferencedFiles (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63486:16)
1:45:55 PM webpack.1  |      at findSourceFile (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63471:21)
1:45:55 PM webpack.1  |      at processSourceFile (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63378:27)
1:45:55 PM webpack.1  |      at processRootFile (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:63265:13)
1:45:55 PM webpack.1  |      at C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:62614:60
1:45:55 PM webpack.1  |      at Object.forEach (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:1293:30)
1:45:55 PM webpack.1  |      at Object.createProgram (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:62614:16)
1:45:55 PM webpack.1  |      at synchronizeHostData (C:\NSKendo\ng2-dashboard\node_modules\typescript\lib\typescript.js:79362:33)
[DONE] Killing all processes with signal  null
1:45:56 PM webpack.1  Exited Successfully
1:46:51 PM tns-sync.1 |  Timeout waiting for bundle JS file. Giving up.
1:46:51 PM tns-sync.1 |  npm
1:46:51 PM tns-sync.1 |   ERR! Windows_NT 10.0.14393
1:46:51 PM tns-sync.1 |  npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MILOSJURAK\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ns-start-sync-android"
1:46:51 PM tns-sync.1 |  npm ERR! node v6.9.4
1:46:51 PM tns-sync.1 |  npm ERR! npm  v4.1.1
1:46:51 PM tns-sync.1 |  npm ERR! code ELIFECYCLE
1:46:51 PM tns-sync.1 |  npm
1:46:51 PM tns-sync.1 |  ERR! angular2-webpack-starter@5.0.5 ns-start-sync-android: `node config/wait-for-bundle.js android && npm run ns-livesync-android`
1:46:51 PM tns-sync.1 |  npm ERR! Exit status 1
1:46:51 PM tns-sync.1 |  npm ERR!
1:46:51 PM tns-sync.1 |  npm ERR! Failed at the angular2-webpack-starter@5.0.5 ns-start-sync-android script 'node config/wait-for-bundle.js android && npm run ns-livesync-android'.
1:46:51 PM tns-sync.1 |  npm ERR! Make sure you have the latest version of node.js and npm installed.
1:46:51 PM tns-sync.1 |  npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
1:46:51 PM tns-sync.1 |  npm ERR! not with npm itself.
1:46:51 PM tns-sync.1 |  npm ERR! Tell the author that this fails on your system:
1:46:51 PM tns-sync.1 |  npm ERR!     node config/wait-for-bundle.js android && npm run ns-livesync-android
1:46:51 PM tns-sync.1 |  npm ERR! You can get information on how to open an issue for this project with:
1:46:51 PM tns-sync.1 |  npm ERR!     npm bugs angular2-webpack-starter
1:46:51 PM tns-sync.1 |  npm ERR! Or if that isn't available, you can get their info via:
1:46:51 PM tns-sync.1 |  npm ERR!     npm owner ls angular2-webpack-starter
1:46:51 PM tns-sync.1 |  npm ERR! There is likely additional logging output above.
1:46:51 PM tns-sync.1 |  npm ERR! Please include the following file with any support request:
1:46:51 PM tns-sync.1 |  npm ERR!     C:\NSKendo\ng2-dashboard\npm-debug.log
1:46:51 PM tns-sync.1 Exited with exit code null

I also tried:
 delete node_module, hooks and platforms folders
 npm cache clear
 tns run android

then at least emulator started but it showed an exception:
![nsdashboardex](https://cloud.githubusercontent.com/assets/12496359/22511819/2de55b38-e897-11e6-86d1-d0fda66c6507.jpg)

and also "COPY TO CLIPBOARD" button is not working

I am using:
npm v 4.1.1
node 6.9.4
tns 2.4.2

My another application created by "NativeScript Getting Started Guide" is working fine.

**Comment by tsvetomir** [comment]
Apologies for letting this fall through.
Please feel free to give it another shot, the project structure is quite different now.
