### ISSUE TITLE
Error throw while installing node_modules npm install

### ISSUE THREAD

**Issue by muraray** [telerik/ng2-dashboard#20]
**Got into this issue while installing the npm install command

D:\KendoUI\ng2-dashboard>npm install
npm WARN deprecated angular2-hmr@0.8.1: please install @angularclass/hmr
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\NodeJS\\node.exe" "C:\\Program Files\\NodeJS\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code E404

npm ERR! 404 Not found : @progress/kendo-angular-dialog
npm ERR! 404
npm ERR! 404 '@progress/kendo-angular-dialog' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404 It was specified as a dependency of 'angular2-webpack-starter'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Others\Samples\Javascript\KendoUI\ng2-dashboard\npm-debug.log

D:\KendoUI\ng2-dashboard>

Am i missing something here?

**Comment by tsvetomir** [comment]
Apologies for letting this fall through.
Please feel free to give it another shot, the project structure is quite different now.
