### ISSUE TITLE
npm install Erro

### ISSUE THREAD

**Issue by at77ms** [telerik/ng2-dashboard#21]
D:\ng\kendo-dashboard>cnpm install
x Install fail! Error: [@progress/kendo-angular-buttons@^0.13.3] GET https://reg
istry.npm.taobao.org/@progress%2Fkendo-angular-buttons/%3E%3D0.13.3%20%3C0.14.0
response 404 status
Error: [@progress/kendo-angular-buttons@^0.13.3] GET https://registry.npm.taobao
.org/@progress%2Fkendo-angular-buttons/%3E%3D0.13.3%20%3C0.14.0 response 404 sta
tus
    at get (d:\node\node_modules\cnpm\node_modules\npminstall\lib\get.js:51:17)
    at get.next (<anonymous>)
    at onFulfilled (d:\node\node_modules\cnpm\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
npminstall version: 2.30.0
npminstall args: d:\node\node.exe d:\node\node_modules\cnpm\node_modules\npminst
all\bin\install.js --china --userconfig=d:\Users\asnphlr\.cnpmrc --disturl=https
://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org

win 7 x64
node v7.10.0
npm  4.2.0

**Comment by at77ms** [comment]
i search in npmjs.com, there no such 'kendo-angular-buttons' module in the npm

**Comment by donaldhook** [comment]
I get all kinds of errors trying to run npm install

npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\yargs-parser-1a8f0552\lib\tokenize-arg-string.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\yargs-parser-1a8f0552\CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\protractor-f101def1\built\debugger\debuggerCommons.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\popper.js-8fd90f75\dist\umd\popper-utils.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\karma-1a4ccc3d\lib\init\color_schemes.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\forms-f428e62d\bundles\forms.umd.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\karma-1a4ccc3d\lib\init\formatters.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\popper.js-8fd90f75\dist\umd\popper-utils.min.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\karma-1a4ccc3d\lib\init\state_machine.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\entry_points.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\popper.js-8fd90f75\dist\umd\popper.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\module_filename_resolver.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\api.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\cli-f29e61d1\ember-cli\lib\cli\cli.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\node_emitter.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\cli-f29e61d1\ember-cli\lib\cli\index.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\node_emitter_transform.js'
npm WARN tar ENOENT: no such file or directory, lstat 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@progress\kendo-angular-excel-export-7fd9a6d0\dist\npm\columns'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\cli-f29e61d1\ember-cli\lib\cli\lookup-command.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\program.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\node_emitter.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\api.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\module_filename_resolver.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\entry_points.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\api.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\node_emitter.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\common-bd398e89\@angular\common\http.es5.js'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\node_emitter_transform.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\entry_points.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\node_emitter_transform.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\program.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\module_filename_resolver.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\transformers\program.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\version.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\extractor.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\compiler-cli-b08267b1\src\version.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\zone.js-5bf9a538\lib\common\error-rewrite.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\zone.js-5bf9a538\lib\common\events.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\zone.js-5bf9a538\lib\common\promise.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\zone.js-5bf9a538\lib\common\timers.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\zone.js-5bf9a538\lib\common\to-string.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\jasmine-spec-reporter-3d11239d\examples\typescript\spec\support\jasmine.json'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\zone.js-5bf9a538\lib\common\utils.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@schematics\angular-5fe18ff2\guard\files\__path__\__name@dasherize__.guard.spec.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@schematics\angular-5fe18ff2\guard\files\__path__\__name@dasherize__.guard.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\router-ecc13a5a\upgrade\package.json'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\router-ecc13a5a\upgrade\index.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'D:\workspace\angular4\ng2-dashboard\node_modules\.staging\@angular\router-ecc13a5a\upgrade\index.metadata.json'
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @progress/kendo-angular-l10n@1.0.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'angular-native-seed'
npm ERR! notarget

**Comment by tsvetomir** [comment]
I have no trouble installing the packages with npm 5.5.1 and node 6.12.0
