### ISSUE TITLE
Title overlaps tabs on mobile

### ISSUE THREAD

**Issue by tsvetomir** [telerik/ng2-dashboard#28]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
The report title overlaps the tab headers on small-ish screens:

![image](https://user-images.githubusercontent.com/247917/38195966-fdde8eb4-3688-11e8-9e0a-5c142f67219d.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Open https://telerik.github.io/ng2-dashboard/#/dashboard on a mobile phone or toggle device emulation in the browser developer tools.

* **What is the expected behavior?**

Perhaps the title should appear above the tabs.

* **Please tell us about your environment:**

- Browser: iOS 11 Safar

**Comment by elena-gancheva** [comment]
Fixed and deployed.
