### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by MarouenAbdi** [telerik/ng2-dashboard#31]
Hi , 

I'm trying to use your project i found it awesome , but i can't understand how the routes are made ! (i'm new with angular) . And i have added a databinding in the signin component so it redirects me straight to main page when i open the project .

**Comment by tsvetomir** [comment]
This issue tracker is focused on the Kendo UI integration. For general guidance, consult the [Angular Routing docs](https://angular.io/tutorial/toh-pt5).

Questions specific to the project structure should be posted to the [TeamMaestro/angular-native-seed](https://github.com/TeamMaestro/angular-native-seed) seed issue tracker.
